# Generated by Django 5.0.1 on 2024-01-13 18:36

import file_storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to=file_storage.models.user_directory_path),
        ),
    ]
